name: Deploy PAT to Azure Web App (OIDC - Auto)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PHP_VERSION: '8.2'
  AZURE_WEBAPP_NAME: 'PAT'
  PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, pdo, pdo_mysql, openssl, json, xml, fileinfo, tokenizer, bcmath, ctype

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      # LOGIN tramite OIDC usando i secrets generati da Azure
      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_18F927BB9DCB481B8BDA501936AA201C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A6A078E7BFA24BE1886EC9DD0EE3EBBA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5C0B14473F214219B4E380CB83130251 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.PACKAGE_PATH }}
